### ISSUE TITLE
Use CI for automatic testing

### ISSUE THREAD

**Issue by AmaiKinono** [AmaiKinono/citre#26]
In #24, I said:

I plan to use <https://github.com/purcell/setup-emacs>. With it we can test on multiple Emacs versions. An example (from [here](https://emacs-china.org/t/emacs-ci/12103)):

``` yml
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.1
          - 25.3
          - 26.1
          - 26.3
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/checkout@v1
    - name: Run tests
      run: 'emacs -Q --batch -L . -f batch-byte-compile *.el'
```
---
@masatake said:

> I plan to use https://github.com/purcell/setup-emacs. With it we can test on multiple Emacs versions. An example (from here):

Nice.

You may need a way to build readtags at the CI environment.
See https://github.com/universal-ctags/ctags/blob/master/.github/workflows/c-cpp.yml
